<?php

// This file was generated by running "composer dump-env prod" for prod

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'your_app_secret',
  'APP_DEBUG' => '0',
  'DATABASE_URL' => 'your_database_url',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => 'your_passphrase',
  'CORS_ALLOW_ORIGIN' => 'allowed_url',
  'STRIPE_SECRET_KEY' => 'your_stripe_secret_key',
  'STRIPE_ENDPOINT_SECRET' => 'your_stripe_endpoint_secret',
  'DOMAIN' => 'your_domain',
);
